# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(max_length=255, unique=True)),
                ('bot_token', models.CharField(max_length=45)),
                ('product_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easybot.Bot')),
            ],
        ),
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=10)),
                ('bot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easybot.Bot')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to=b'')),
                ('bot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easybot.Bot')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easybot.Category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.TextField()),
                ('email', models.EmailField(max_length=60)),
                ('phone_number', models.CharField(max_length=10)),
                ('bot_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='easybot.Bot')),
            ],
        ),
        migrations.AddField(
            model_name='costumer',
            name='product_list',
            field=models.ManyToManyField(null=True, to='easybot.Product'),
        ),
    ]
