# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=20)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=20, null=True, unique=True)),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=20, null=True, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('state', models.CharField(default='null', max_length=255)),
                ('current', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Like_dislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=20)),
                ('like', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30, null=True)),
                ('text', models.TextField(null=True)),
                ('image', models.CharField(max_length=60, null=True)),
                ('price', models.IntegerField(null=True)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easybot.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('text_comment', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sabad_Kharid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easybot.Customer')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easybot.Product')),
            ],
        ),
        migrations.AddField(
            model_name='like_dislike',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easybot.Product'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='easybot.Feedback_cat'),
        ),
        migrations.AlterUniqueTogether(
            name='sabad_kharid',
            unique_together=set([('cus_id', 'p_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='like_dislike',
            unique_together=set([('telegram_id', 'p_id')]),
        ),
    ]
