# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
