# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='product_name',
        ),
    ]
