# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0002_auto_20170604_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_cat',
            field=models.IntegerField(null=True),
        ),
    ]
