# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0002_remove_bot_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=20, null=True)),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=20, null=True, unique=True)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sabad_Kharid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='easybot.Customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='bot_id',
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='product_list',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bot_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='bot_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bot_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='cat_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='cat_id',
        ),
        migrations.AddField(
            model_name='product',
            name='cat_id',
            field=models.ManyToManyField(to='easybot.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='text',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.DeleteModel(
            name='Bot',
        ),
        migrations.DeleteModel(
            name='Costumer',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='sabad_kharid',
            name='p_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='easybot.Product'),
        ),
    ]
