# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0003_auto_20170605_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='like_dislike',
            name='s',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
