# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0004_like_dislike_s'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like_dislike',
            name='s',
        ),
    ]
