# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0005_remove_like_dislike_s'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='current_cat',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
