# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0005_auto_20170527_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cat_id',
        ),
        migrations.AddField(
            model_name='product',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easybot.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sabad_kharid',
            name='cus_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easybot.Customer'),
        ),
        migrations.AlterField(
            model_name='sabad_kharid',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easybot.Product'),
        ),
    ]
