# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0006_auto_20170528_1601'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sabad_kharid',
            unique_together=set([('cus_id', 'p_id')]),
        ),
    ]
