# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-15 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0006_customer_current_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_info', models.TextField(null=True)),
                ('cus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easybot.Customer')),
            ],
        ),
    ]
