# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-15 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='numbers',
            field=models.IntegerField(null=True),
        ),
    ]
