# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0008_auto_20170528_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
