# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-15 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0008_product_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='sabad_kharid',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
