# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0009_customer_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('cus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easybot.Customer')),
            ],
        ),
    ]
