# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-19 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0010_sabad_kharid_ordered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_to_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='sabad_kharid',
            name='ordered',
        ),
        migrations.AddField(
            model_name='order',
            name='order_time',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order_to_product',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easybot.Order'),
        ),
        migrations.AddField(
            model_name='order_to_product',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easybot.Product'),
        ),
    ]
