# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-20 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0011_auto_20171019_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='arrived',
            field=models.IntegerField(default=0),
        ),
    ]
