# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0011_auto_20170530_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='current',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
