# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0012_customer_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
