# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-21 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0012_order_arrived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='arrived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='numbers',
            field=models.IntegerField(default=1),
        ),
    ]
