# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0013_auto_20170601_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('text_comment', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
