# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0013_auto_20170601_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='like_dislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=20)),
                ('like', models.BooleanField()),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easybot.Product')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='like_dislike',
            unique_together=set([('telegram_id', 'p_id')]),
        ),
    ]
