# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0013_auto_20171021_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peyk_motori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=20, null=True, unique=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easybot.Order')),
            ],
        ),
    ]
