# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0014_peyk_motori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='arrived',
            field=models.IntegerField(default=1),
        ),
    ]
