# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0015_auto_20171029_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True)),
                ('text', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to=b'')),
            ],
        ),
    ]
