# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-08 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0015_auto_20171107_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveys',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
