# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0018_customer_email'),
        ('easybot', '0014_auto_20171104_1151'),
    ]

    operations = [
    ]
