# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0019_merge_20171107_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_char', models.CharField(default=None, max_length=30)),
            ],
        ),
    ]
