# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0016_auto_20171108_1611'),
        ('easybot', '0020_discountcode'),
    ]

    operations = [
    ]
