# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0026_auto_20171110_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveys',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
