# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-11 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0022_auto_20171110_2037'),
        ('easybot', '0026_auto_20171110_1701'),
    ]

    operations = [
    ]
