# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0027_auto_20171110_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default=None)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easybot.Questions')),
            ],
        ),
    ]
