# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-12 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0027_merge_20171111_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default=None)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easybot.Questions')),
            ],
        ),
        migrations.AlterField(
            model_name='advertise',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='surveys',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
