# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0028_auto_20171112_1512'),
        ('easybot', '0028_answers'),
    ]

    operations = [
    ]
