# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-27 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0033_auto_20171208_0539'),
        ('easybot', '0033_auto_20171214_2241'),
    ]

    operations = [
    ]
