# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-30 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0037_transactions_amount'),
        ('easybot', '0035_auto_20180128_1329'),
    ]

    operations = [
    ]
