# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-30 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easybot', '0038_merge_20180130_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
