# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=20, null=True, unique=True)),
                ('email', models.EmailField(max_length=50, null=True, unique=True)),
                ('bot_name_1', models.CharField(max_length=30, null=True)),
                ('bot_name_2', models.CharField(max_length=30, null=True)),
                ('bot_name_3', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
