# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botowner',
            name='transaction_number',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
